# Generated by Django 3.1.5 on 2021-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('camera_number', models.CharField(blank=True, default='Door', max_length=5)),
                ('behaviour', models.CharField(blank=True, default='Not walking on sidewalk', max_length=50)),
                ('name', models.CharField(blank=True, default='NULL', max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('video', models.FileField(blank=True, default='NULL', upload_to='videos/')),
            ],
        ),
    ]
