# Generated by Django 3.2.7 on 2021-09-08 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='violations',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 13, 15, 26, 966468)),
        ),
    ]
