# Generated by Django 4.0.2 on 2022-02-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database_app', '0004_alter_violations_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Violations',
            new_name='Detections',
        ),
    ]
