# Generated by Django 4.0.2 on 2022-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database_app', '0005_rename_violations_detections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detections',
            name='id',
        ),
        migrations.AddField(
            model_name='detections',
            name='serial_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
