# Generated by Django 4.0.2 on 2022-02-13 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Database_app', '0010_alter_detections_result_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
        ),
    ]
